project:
  name: cfn-{{ cookiecutter.module_name }}
  regions:
  - us-east-1
tests:
  default:
    template: ./vpc.json
    parameters:
      Owner: CCOwner
      Environment: CCEnvironment
      Project: CCProject