project:
  name: {{ cookiecutter.__project_slug}}
  regions:
  - us-east-2
tests:
  default:
    template: ./{{cookiecutter.module_name}}.json
    parameters:
      Owner: CCOwner
      Environment: CCEnvironment
      Project: CCProject