project:
  name: cfn-{{ cookiecutter.module_name }}
  regions:
  - us-east-2
tests:
  default:
    template: ./{{cookiecutter.module_name}}.json
    parameters:
      Owner: CCOwner
      Environment: CCEnvironment
      Project: CCProject